pnr_innovus:
  dependency:
    - floorplan:
        out: place.pass
        cmd: place.tcl
        sub_steps:
          import_design.tcl: pnr_innovus::import_design
          load_scan_def.tcl: pnr_innovus::load_scan_def
          load_power_intent.tcl: pnr_innovus::load_power_intent
          config_design.tcl: pnr_innovus::config_design
          config_timing.tcl: pnr_innovus::config_timing
          init_fplan.tcl: pnr_innovus::init_fplan
          load_fplan_snapshot.tcl: pnr_innovus::load_fplan_snapshot
          legalize_macro.tcl: pnr_innovus::legalize_macro
          add_endcap.tcl: pnr_innovus::add_endcap
          add_welltap.tcl: pnr_innovus::add_welltap
          route_power.tcl: pnr_innovus::route_power
          add_ip_pg.tcl: pnr_innovus::add_ip_pg
          legalize_pin_assignment.tcl: pnr_innovus::legalize_pin_assignment
          capture_fplan_snapshot.tcl: pnr_innovus::capture_fplan_snapshot
          add_port_affinity.tcl: pnr_innovus::add_port_affinity
          save_design.tcl: pnr_innovus::save_design
          report_design.tcl: pnr_innovus::report_design
          check_pd.tcl: pnr_innovus::check_pd
          save_metrics.tcl: pnr_innovus::save_metrics

    - place:
        out: place.pass
        cmd: place.tcl
        sub_steps:
          innovus_restore_design.tcl: pnr_innovus::restore_design
          innovus_config_design.tcl: pnr_innovus::config_design
          innovus_add_tie_cell.tcl: pnr_innovus::add_tie_cell
          innovus_save_design.tcl: pnr_innovus::save_design
          innovus_report_design.tcl: pnr_innovus::report_design
          innovus_check_pd.tcl: pnr_innovus::check_pd
          innovus_save_metrics.tcl: pnr_innovus::save_metrics
    - postroute:
        in: place.pass
        out: postroute.pass
        cmd: postroute.tcl
